apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sso
  labels:
    application: sso
  annotations:
    description: "Route for application's https service."
spec:
  to:
    kind: Service
    name: sso
    weight: 100
  port:
    targetPort: 8443
  tls:
    termination: reencrypt
