apiVersion: V1
kind: ConfigMap
metadata:
  name: sso-service-ca
  labels:
    application: sso
  annotations:
    description: "ConfigMap providing service ca bundle."
    service.beta.openshift.io/inject-cabundle: true
